---
locale: es
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: Nada es mejor, nada es igual… Bueno igual puede ser!
